version: '3.3'
services:
  user_ms:
    container_name: user_ms
    hostname: user_ms
    build:
      context: .
      dockerfile: devops/Dockerfile
    volumes:
      - "./:/usr/src/app"
    environment:
      - PORT=4000
      - POSTGRES_HOST=user_ms_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE_NAME=user-authentication
    command: npm run start:dev
    ports:
      - "4000:4000"
    networks:
      - default_network
  user_ms_db:
    container_name: user_ms_db
    hostname: user_ms_db
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    networks:
      - default_network
networks:
  default_network:
    name: default_network
    driver: bridge
    external: true